### ISSUE TITLE
draft-markup NPM module still pointed here

### ISSUE THREAD

**Issue by jc4p** [GitbookIO/markup-it#28]
It seems that you're working on migrating the React specific portions of this repo out and into https://github.com/GitbookIO/react-markup-editor -- but https://www.npmjs.com/package/draft-markup is still pointing to this Git repo. I think the NPM module needs to be deprecated or include a notice that it's no longer under development as-is on that page, NPM has good SEO and this just sent me down a weird rabbithole of "Why isn't it working?!"

**Comment by SamyPesse** [comment]
Thank you.

I've deprecated `draft-markup` on NPM, we're no longer working on Draft.js and `react-markup-editor`.
