### ISSUE TITLE
nested lists are not rendered correctly

### ISSUE THREAD

**Issue by frabrunelle** [GitbookIO/markup-it#29]
```
* One
  * sub-one
  * sub-two
* Two
* Three
```

On GitBook, this is rendered as:

``` html
<ul>
  <li>
    <p>One</p>
    <ul>
      <li>sub-one</li>
      <li>sub-two</li>
    </ul>
  </li>
  <li><p>Two</p></li>
  <li>Three</li>
</ul>
```

But on GitHub and [CommonMark](http://spec.commonmark.org/dingus/?text=*%20One%0A%20%20*%20sub-one%0A%20%20*%20sub-two%0A*%20Two%0A*%20Three), it's rendered as:

``` html
<ul>
  <li>
    One
    <ul>
      <li>sub-one</li>
      <li>sub-two</li>
    </ul>
  </li>
  <li>Two</li>
  <li>Three</li>
</ul>
```

I prefer the version without paragraphs, otherwise it adds unnecessary margins between some of the list items. For now, I've added the following CSS rule to my GitBook, but it would be great if this could be fixed 😃 

``` css
.markdown-section li > p {
  margin-bottom: 0 !important;
}
```

**Comment by SamyPesse** [comment]
Thanks, Fixed in `3.0.0` (with associated tests).
