### ISSUE TITLE
Newlines in paragraph are not converted to spaces

### ISSUE THREAD

**Issue by Soreine** [GitbookIO/markup-it#59]
```
Hello
World
```

without two trailing spaces, will generate a break:

Hello
World

**Comment by SamyPesse** [comment]
GitHub doesn't respect the [markdown syntax](https://daringfireball.net/projects/markdown/syntax#p).

But `markdown-it` Markdown preview on atom, etc respect it:

<img width="528" alt="screen shot 2017-01-24 at 17 38 42" src="https://cloud.githubusercontent.com/assets/845425/22256761/0f79ebfa-e25c-11e6-8c71-7de2abb81ea4.png">

@Soreine do you think we should support GitHub syntax or the official one ?

**Comment by Soreine** [comment]
We know we like the GitHub syntax. And it's the legacy syntax in GitBook
