### ISSUE TITLE
Line separator should not be "/n" (sic)

### ISSUE THREAD

**Issue by bazzargh** [GitbookIO/markup-it#76]
https://github.com/GitbookIO/markup-it/blob/ad90bfb0e28763568fc2d16c155cf821befc4d76/src/html/parse.js#L303

^ found this reading the code. It's falling back on using "/n" not "\n" as the line break if detection fails, which is nonsensical. detect-newline already contains code to cover this - detectNewline.graceful(x) will return "\n" for this case.
https://github.com/sindresorhus/detect-newline/blob/master/index.js#L23

**Comment by SamyPesse** [comment]
Closed by #77
