### ISSUE TITLE
Text.getRanges method is deprecated in slatejs

### ISSUE THREAD

**Issue by ChongShao** [GitbookIO/markup-it#90]
console will throw an error : Uncaught TypeError: text.getRanges is not a function

The Text.getRanges() method is now Text.getLeaves(), please update the method.

**Comment by wagon1104** [comment]
console will throw an error : Uncaught TypeError: text.getRanges is not a function

The Text.getRanges() method is now Text.getLeaves(), please update the method.

**Comment by SamyPesse** [comment]
Fixed by #94
